from .client import SkroutzClient as client
from .resources.books import Books as books
from .resources.categories import Categories as categories
from .resources.favorites import Favorites as favorites
from .resources.flags import Flags as flags
from .resources.manufacturers import Manufacturers as manufacturers
from .resources.products import Products as products
from .resources.skus import Skus as skus
from .resources.users import Users as user
